config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'venues#index'
  resources :venues do
    resources :bookings
  end
  get "my_bookings", to: "bookings#my_bookings", as: :my_bookings
  get "my_venues", to: "venues#my_venues", as: :my_venues
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :venue
  has_one_attached :qrcode
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_venue, only: [:new, :create, :edit, :update, :show, :total_price]
  before_action :set_booking, only: [:show, :destroy, :edit, :update]

  def show
    unless @booking.user == current_user
      redirect_to venues_path, status: :see_other, alert: "You are not authorized to see this booking"
    end
  end

  def new
    @booking = Booking.new
    # redirect_to venue_path(@list.id), status: :see_other
  end


  def create
    @booking = Booking.new(booking_params)
    @booking.venue = Venue.find(params[:venue_id])
    @booking.user = current_user

    if @booking.save!
##QR CODE
      link = venue_booking_url(@booking.venue, @booking)
      qrcode = RQRCode::QRCode.new(link)
      png = qrcode.as_png(
        bit_depth: 1,
        border_modules: 4,
        color_mode: ChunkyPNG::COLOR_GRAYSCALE,
        color: "black",
        file: nil,
        fill: "white",
        module_px_size: 6,
        resize_exactly_to: false,
        resize_gte_to: false,
        size: 120
      )
      ##Using MiniMagick to resize the QR code and place it on the venue image

      qr_image = MiniMagick::Image.read(png.to_s)
      #here i pass the main image of the venue on the QR code
      background = MiniMagick::Image.open(@booking.venue.photos.first)

      # resize the QR code to be 90% of the background image's smallest dimension
      smaller_dimension = [background.width, background.height].min
      qr_size = (smaller_dimension * 0.9).round

      # resize the QR code
      qr_image.resize "#{qr_size}x#{qr_size}"

      # calculate the position where the QR code should be placed in order to be centered
      qr_position_x = ((background.width - qr_image.width) / 2).round
      qr_position_y = ((background.height - qr_image.height) / 2).round

      result = background.composite(qr_image) do |c|
        c.compose "Over"    # OverCompositeOp
        c.geometry "+#{qr_position_x}+#{qr_position_y}" # position of QR code on the background image
      end

      # Draw user's name at the top
      result.combine_options do |c|
        c.gravity 'North'
        c.pointsize '40'
        c.draw "text 0,60 '#{current_user.first_name} #{current_user.last_name}'"
        c.fill 'black'
      end

      # Draw dates at the bottom
      result.combine_options do |c|
        c.gravity 'South'
        c.pointsize '40'
        c.draw "text 0,40 'From: #{@booking.start_date.strftime("%d/%m/%Y")} to #{@booking.end_date.strftime("%d/%m/%Y")}'"
        c.fill 'black'
      end

      result.write("composite_image.png") # replace with actual path where you want to store it
      @booking.qrcode.attach(io: File.open("composite_image.png"), filename: "qr_code.png", content_type: "image/png")

##END OF QR CODE

      @booking.save!
      redirect_to venue_booking_path(@booking.venue, @booking), status: :see_other
    else
      render :new
    end
  end

  def edit
  end

  def update
    @booking = Booking.find(params[:id])
    if @booking.update(booking_params)
      redirect_to venue_booking_path(@booking.venue, @booking), status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @booking.destroy
    redirect_to my_bookings_path
  end

  def my_bookings
    @my_bookings = current_user.bookings
    if @my_bookings.empty?
      redirect_to venues_path, status: :see_other
    end
  end

  def total_price(start_date, end_date, venue)
    @booking = booking
    @venue = venue
    @total_days = (end_date - start_date).to_i + 1
    @total_days
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :total_price)
  end

  def set_venue
    @venue = Venue.find(params[:venue_id])
  end
end

app/views/bookings/edit.html.erb
<h1>Bookings#edit</h1>
<div class="position-relative m-3">
  <div class="col-12 col-md-6 offset-lg-3">
    <div class="bg-white rounded p-3 shadow">
      <%= simple_form_for [@venue, @booking] do |f| %>
        <%= f.input :start_date, as: :date, html5: true, input_html: { min: Date.current.to_s, id: 'start-date' } %>
        <%= f.input :end_date, as: :date, html5: true, input_html: { id: 'end-date' } %>
        <%= f.submit "Update", class: "btn btn-outline-dark" %>
      <% end %>
    </div>
  </div>
</div>

<script>
  document.addEventListener("DOMContentLoaded", function() {
    var startDateInput = document.getElementById('start-date');
    var endDateInput = document.getElementById('end-date');

    startDateInput.addEventListener("input", function() {
      endDateInput.min = startDateInput.value;
      if (endDateInput.value < startDateInput.value) {
        endDateInput.value = startDateInput.value;
      }
    });
  });
</script>

app/views/bookings/my_bookings.html.erb
<div class="container mx-auto mt-4">
  <h1>My bookings</h1>
<div class="container mx-auto mt-4">
  <div class="row">
    <% @my_bookings.each do |booking| %>
      <div class="col-lg-3 my-3">
        <div class="card" style="width: 18rem; height: 22rem;">
          <% if booking.venue.photos.attached? %>
            <img src="<%= cl_image_path booking.venue.photos.first.key %>" class="card-img-top" alt="Listing Image">
          <% end %>
          <div class="card-body position-relative">
            <h5 class="card-title"><%= booking.venue.title %></h5>
            <h6 class="card-subtitle mb-2 text-muted"></h6>
            <p class="card-text position-absolute bottom-0 start-2 fw-bold">
          Cost:  <%= (((booking.end_date - booking.start_date)+ 1).to_i * booking.venue.daily_rate).to_f %>€</p><br>
            Booked for <%= (booking.end_date - booking.start_date).to_i + 1 %> days
            <%= link_to "Details", venue_booking_path(booking.venue, booking), class: "btn btn-outline-dark position-absolute bottom-0 end-0 m-2" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/bookings/new.html.erb
<h1>Bookings#new</h1>
<p>Find me in app/views/bookings/new.html.erb</p>

app/views/bookings/show.html.erb
<div class="container col-lg-12 my-3">
  <div class="card my-3">
    <div class="banner">
      <img src="<%= cl_path @booking.venue.photos.first.key %>" class="card-img-top-banner-img" alt="Listing Image">
    </div>
  </div>
      <div class="card">
        <h5 class="card-title"><%= @venue.title %></h5>
        <h6 class="card-subtitle mb-2 text-muted"></h6>
        <p class="card-text"><%= @venue.description %></p>
        <hr>
              <p>  You booked the venue from the <%= @booking.start_date.strftime("%d/%m/%Y") %>to the  <%= @booking.end_date.strftime("%d/%m/%Y") %> (for a total of <%= ((@booking.end_date - @booking.start_date)+1).to_i %> days).

     <p>     Your total price is <b><%= (((@booking.end_date - @booking.start_date)+1).to_i * @booking.venue.daily_rate).to_f %>€.</b>
     <p>

        <p class="card-text position-absolute bottom-0 start-2 fw-bold">

        <p class="card-text position-absolute bottom-0 end-0 fw-bold">

          <% if @booking.qrcode.attached? %>
          <%= cl_image_tag(@booking.qrcode.key, width: 300, alt: "QR code for booking") %>
          <% end %>

      </div>
  <%= link_to "My bookings", my_bookings_path, class: "btn btn-outline-dark" %>
  <%= link_to "Edit",edit_venue_booking_path(@venue, @booking), class: "btn btn-outline-dark"%>
  <%= link_to "Delete",venue_booking_path(@venue.id, @booking.id), class: "btn btn-outline-danger",
  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}%>
</div>
<br><br><br>

app/views/bookings/update.html.erb
<h1>Bookings#update</h1>
<p>Find me in app/views/bookings/update.html.erb</p>