config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'venues#index'
  resources :venues do
    resources :bookings
  end
  get "my_bookings", to: "bookings#my_bookings", as: :my_bookings
  get "my_venues", to: "venues#my_venues", as: :my_venues
end

app/models/venue.rb
class Venue < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :invitees, through: :bookings, source: :user
  validates :title, presence: true
  validates :address, presence: true
  validates :description, presence: true
  validates :surface_area, presence: true
  validates :daily_rate, presence: true

  has_many_attached :photos
  has_one_attached :video
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  before_action :set_venue, only: [ :edit, :update, :show, :destroy, :my_venues ]


  def index
    @venues = Venue.all
    @categories = {
      "Bar/Club" => "fa-solid fa-beer-mug-empty",
      "Office" => "fa-regular fa-building",
      "Restaurant" => "fa-solid fa-utensils",
      "Storefront" => "fa-solid fa-shop"
    }
  end

  def show
    @booking = Booking.new
    @categories = {
      "Bar/Club" => "fa-solid fa-beer-mug-empty",
      "Office" => "fa-regular fa-building",
      "Restaurant" => "fa-solid fa-utensils",
      "Storefront" => "fa-solid fa-shop"
    }
  end

  def new
    @venue = Venue.new
    @categories = ["Bar/Club", "Office", "Restaurant", "Storefront"]

  end

  def create
    @venue = Venue.new(venue_params)
    @venue.user = current_user
    if @venue.save
      redirect_to venues_path, status: :see_other
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    @venue.update(venue_params)
    redirect_to venue_path(@venue)
  end

  def destroy
    @venue.destroy
    redirect_to venues_path, status: :see_other
  end

  def my_venues
    @my_venues = current_user.venues
  end

  private

  def set_venue
    @venue = Venue.find_by(id: params[:id])
  end

  def venue_params
    params.require(:venue).permit(:title, :address, :description, :img_url, :surface_area, :daily_rate, :venue_type, :has_parking, :has_internet, :has_ac, :video, photos: [])
  end

  def set_booking
    @booking = Booking.find(params[:venue_id])
  end
end

app/views/venues/create.html.erb
<h1>Venues#create</h1>
<p>Find me in app/views/venues/create.html.erb</p>

app/views/venues/destroy.html.erb
<h1>Venues#destroy</h1>
<p>Find me in app/views/venues/destroy.html.erb</p>

app/views/venues/edit.html.erb
<style>
.description-input {
  height: 200px; /* Adjust the height as needed */
}

.boolean-input-container {
  display: flex; /* Display the inputs in a flex container */
}

</style>

<div class="position-relative m-3">
  <div class="col-12 col-md-6 offset-lg-3">
    <div class="bg-white rounded p-3 shadow">
      <h1>List your venue</h1>
      <%= simple_form_for(@venue) do |f| %>
        <%= f.input :title %>
        <%= f.input :address %>
        <%= f.input :description, as: :text, input_html: { class: 'description-input' } %>
        <%= f.input :surface_area, label: "Surface area (square meter)" %>
        <%= f.input :daily_rate %>
        <%= f.input :venue_type, collection: @categories %>

        <div class="boolean-input-container">
          <%= f.input :has_parking %>
          <%= f.input :has_internet %>
          <%= f.input :has_ac %>
        </div>

        <%= f.input :photo, as: :file %>
        <%= f.submit %>
      <% end %>

      <%= link_to "Back", venues_path %>
    </div>
  </div>
</div>

app/views/venues/index.html.erb
<div class="container mx-auto mt-4">
  <h1>Venues</h1>
  <div class="row">
    <% @venues.each do |venue| %>
      <div class="col-lg-4 my-3">
        <div class="card" style="width: 18rem; height: 22rem;">
          <% if venue.photos.attached? %>
            <img src="<%= cl_image_path venue.photos.first.key %>" class="card-img-top" alt="...">
          <% end %>
          <div class="card-body position-relative">
            <h5 class="card-title"><%= venue.title %></h5>
            <h6 class="card-subtitle mb-2 text-muted"><%= venue.venue_type %> <i class="<%= @categories[venue.venue_type] %>"></i></h6>
            <p class="card-text" style="position: absolute; bottom: 0; left: 0; margin: 8px;"><%= venue.daily_rate %>€</p>
            <%= link_to "Details", venue_path(venue), class: "btn btn-outline-dark position-absolute bottom-0 end-0 m-2" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/venues/my_venues.html.erb
<div class="container mx-auto mt-4">
  <h1>My venues</h1>

<div class="container mx-auto mt-4">
  <div class="row">
    <% if @my_venues.empty? %>

    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <h3>You haven't listed any venue yet.<br>Do it by clicking on this link: <br>
                  <%= link_to "List my venue", new_venue_path %>

        </h3>
      <% else %>
        <% @my_venues.each do |v| %>
          <div class="col-lg-3 my-3">
            <div class="card" style="width: 18rem; height: 22rem;">
            <% if v.photos.attached? %>
              <img src="<%= cl_image_path v.photos.first.key %>" class="card-img-top" alt="Listing Image">
            <% end %>
              <div class="card-body position-relative">
                <h5 class="card-title"><%= v.title %></h5>
                <h6 class="card-subtitle mb-2 text-muted"></h6>
                <p class="card-text" style="position: absolute; bottom: 0; left: 0; margin: 8px;"><%= v.daily_rate %>€</p>
                <%= link_to "Details", venue_path(v), class: "btn btn-outline-dark position-absolute bottom-0 end-0 m-2" %>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
  </div>
</div>

app/views/venues/new.html.erb
<style>
.description-input {
  height: 200px; /* Adjust the height as needed */
}

.boolean-input-container {
  display: flex; /* Display the inputs in a flex container */
}

</style>

<div class="position-relative m-3">
  <div class="col-12 col-md-6 offset-lg-3">
    <div class="bg-white rounded p-3 shadow">
      <h1>List your venue</h1>
      <%= simple_form_for(@venue) do |f| %>
        <%= f.input :title %>
        <%= f.input :address %>
        <%= f.input :description, as: :text, input_html: { class: 'description-input' } %>
        <%= f.input :surface_area, label: "Surface area (square meter)" %>
        <%= f.input :daily_rate %>
        <%= f.input :venue_type, collection: @categories %>

        <div class="boolean-input-container">
          <%= f.input :has_parking %>
          <%= f.input :has_internet %>
          <%= f.input :has_ac %>
        </div>

        <%= f.input :photos, as: :file, input_html: { multiple: true } %>
        <%= f.input :video, as: :file %>
        <%= f.submit %>
      <% end %>

      <%= link_to "Back", venues_path %>
    </div>
  </div>
</div>

app/views/venues/show.html.erb
<div class="container">
  <h1><%= @venue.title %></h1>
  <div class="row">
      <div class="col-12 col-lg-8 my-3">
        <div class="card">
          <div class="banner">
            <% if @venue.photos.attached? %>
              <% @venue.photos.each do |photo| %>
                <%= cl_image_tag photo.key, class: "card-img-top" %>
              <% end %>
            <% end %>
            <div class="card-body">
              <h5 class="card-title"><%= @venue.title %></h5>
              <h6 class="card-subtitle mb-2 text-muted"></h6>
              <p class="card-text"><%= @venue.description %></p>
            </div>
          </div>
        </div>
      </div>
      <div class="col-12 col-lg-4 my-3">
        <% if !user_signed_in? || (user_signed_in? && !current_user.owns_this_venue?(@venue)) %>
          <div class="bg-white p-3 shadow">
            <h3>Add a booking to <%= @venue.title%> </h3>
            <%= simple_form_for [@venue, @booking], data: { controller: "price" } do |f| %>
              <%= f.input :start_date, as: :date, html5: true, input_html: { min: Date.current.to_s, id: "start-date", value: Date.today, data: { price_target: "startDate", action: "change->price#updatePrice" } } %>
              <%= f.input :end_date, as: :date, html5: true, input_html: { min: Date.current.to_s, id: "end-date", value: Date.today, data: { price_target: "endDate", action: "change->price#updatePrice" } } %>
              <h4>Daily Rate : </h4> <p data-price-target="price"><%= @venue.daily_rate %>€</p>
              <% if current_user %>
                <%= f.submit class: "btn btn-outline-dark", data: { price_target: "submit" } %>
              <% else %>
              <%= link_to "book", new_user_session_path, class: "btn btn-outline-success" %>
              <% end %>
            </div>
          </div>
        <% end %>

      <% end %>
    </div>
    <div class="col-12 col-lg-4 my-3">
      <% if user_signed_in? && current_user.owns_this_venue?(@venue) %>
        <%= link_to "Edit", edit_venue_path(@venue), class: "btn btn-outline-dark" %>
        <%= link_to "Delete", venue_path(@venue), class: "btn btn-outline-danger",
          data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}%>
      <% end %>
        <%= link_to "Go back", venues_path, class: "btn btn-outline-dark" %>
  </div>
  </div>
</div>
<br><br><br>

app/views/venues/update.html.erb
<h1>Venues#update</h1>
<p>Find me in app/views/venues/update.html.erb</p>