config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'venues#index'
  resources :venues do
    resources :bookings
  end
  get "my_bookings", to: "bookings#my_bookings", as: :my_bookings
  get "my_venues", to: "venues#my_venues", as: :my_venues
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
  <title>CHANGEThisToYourRailsAppName</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  <script src="https://kit.fontawesome.com/93217e7224.js" crossorigin="anonymous"></script>
  <style>
    @media (max-width: 991.98px) {
      .navbar {
        flex-wrap: wrap;
      }
      .navbar-toggler {
        order: 1;
        width: 100%;
        text-align: right;
        padding-right: 15px; /* adjust as necessary */
      }
      .navbar-collapse {
        order: 2;
        width: 100%;
      }
      .navbar-nav {
        display: flex;
        align-items: center;
        flex-wrap: nowrap;
      }
    }
  </style>
</head>

<body>
  <%# BEGINNING OF THE NAV BAR %><nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-dark border-bottom-dark bg-body-tertiary" data-bs-theme="dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="<%= venues_path %>">
            <img src="<%= asset_path('popupshop-low-resolution-logo-color-on-transparent-background.png') %>" style="width: 8%; height: auto;" alt="PopUpShop">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <% if user_signed_in? %>
                <div class="row navbar-nav ms-auto mb-2 mb-lg-0 align-items-center">
                    <div class="col d-flex justify-content-end">
                        <li class="nav-item">
                            <div class="d-flex ">
                                <a class="btn btn-outline-danger" href="<%= new_venue_path %>">List my venue</a>
                            </div>
                        </li>
                    </div>
                    <div class="col d-flex justify-content-start">
                        <li class="nav-item dropdown px-4">
                            <a class="nav-link dropdown-toggle text-white" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Hi <%= current_user.first_name %>!
                                  <% if current_user.avatar.attached? %>
                                    <img src="<%= cl_image_path current_user.avatar.key %>" alt="Profile Picture" class="rounded-circle" style="width: 40px; height: 40px;">
                                  <% else %>
                                    <img src="<%= asset_path('profile-icon-9.png') %>" alt="Profile Logo" class="rounded-circle" style="width: 40px; height: 40px;">
                                  <% end %>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item text-white" href="<%= edit_user_registration_path %>">Profile</a></li>

                                <% unless current_user.bookings.empty? %>
                                  <li><a class="dropdown-item text-white" href="<%= my_bookings_path %>">My Bookings</a></li>
                                <% end %>
                                <% unless current_user.venues.empty? %>
                                <li><a class="dropdown-item text-white" href="<%= my_venues_path %>">My Venues</a></li>
                                <% end %>
                                <li><hr class="dropdown-divider"></li>
                                <li>
                                    <%= link_to "Log out", destroy_user_session_path, data: { turbo_method: :delete }, class: "dropdown-item text-white" %>
                                </li>
                            </ul>
                        </li>
                    </div>
                </div>
            <% else %>
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0 align-items-center">
                    <li class="nav-item">
                        <div class="d-flex">
                            <a class="btn btn-outline-danger" href="<%= new_venue_path %>">List my venue</a>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active px-4" aria-current="page" href="<%= new_user_session_path %>">Sign-in</a>
                    </li>
                </ul>
            <% end %>
        </div>
    </div>
</nav>

  <%# END OF THE NAV BAR %>

  <%= yield %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-6VLyltKj+Uup9TRfGuAhDtnN8GSe4WbDhMuf5Pmi04gFBJCFaRlC1Iy+lnD17cbk" crossorigin="anonymous" defer></script>
</body>
</html>